name: Deploy Frontend via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
     NAME: 'haider ali'
     BRANCH: '${{ GITHUB_REF_NAME }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get branch name
        id: vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          timeout: 120m
          command_timeout: 60m
          
          script: |
            set -e
            echo "haider ali"
            echo "$Name"
            echo "${{ env.NAME }}"
            echo "${{ env.BRANCH }}"
            echo "Deploying branch: ${{ env.BRANCH_NAME }}"
            echo "End"
            
